name: "Test"

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - unlabeled
    branches:
      - main

permissions: {}

jobs:
  run_the_action:
    name: "Run the action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the local action
        uses: ./
        with:
          labels: >-
            bugfix, breaking-change, new-feature, dependencies
