name: "Test"

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - synchronize
      - unlabeled

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_the_action:
    name: "Run the action (${{ matrix.os }})"
    if: github.event.pull_request.labels[0] != null
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: &os_matrix
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run the local action
        uses: ./
        with:
          labels: >-
            bugfix, breaking-change, new-feature, dependencies, ci, documentation, internal, refactor

  run_the_action_require_exactly_one:
    name: "Run the action (require: 1, ${{ matrix.os }})"
    if: github.event.pull_request.labels[0] != null
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: *os_matrix
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run the local action
        uses: ./
        with:
          labels: >-
            bugfix, breaking-change, new-feature, dependencies, ci, documentation, internal, refactor
          require: 1

  run_the_action_require_none:
    name: "Run the action (require: none, ${{ matrix.os }})"
    if: github.event.pull_request.labels[0] != null
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: *os_matrix
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run the local action
        uses: ./
        with:
          labels: >-
            do-not-merge, wip, blocked
          require: none
